#  Copyright (c) 2025 AshokShau
#  Licensed under the GNU AGPL v3.0: https://www.gnu.org/licenses/agpl-3.0.html
#  Part of the TgMusicBot project. All rights reserved where applicable.

#  NOTE: DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
#  Configure environment variables using the .env file instead

from os import getenv
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

from src.logger import LOGGER

load_dotenv()


def get_env_int(name: str, default: Optional[int] = None) -> Optional[int]:
    """
    Gets an environment variable as an integer, or returns the default value if
    the variable does not exist or is not an integer.

    Args:
        name (str): The environment variable name.
        default (Optional[int]): The default value to return if the variable does not exist.
            Defaults to None.

    Returns:
        Optional[int]: The value of the environment variable as an integer, or the default value.
    """
    value = getenv(name)
    try:
        return int(value)
    except (TypeError, ValueError):
        LOGGER.warning("Invalid value for %s: %s (default: %s)", name, value, default)
        return default


API_ID: Optional[int] = get_env_int("20908081")
API_HASH: Optional[str] = getenv("5972f5fa0de92a847f78f6329518db47")
TOKEN: Optional[str] = getenv("8109694815:AAFFf7YCotAuwuUdWQUkBvLiR8LdkQ832zE")
MIN_MEMBER_COUNT: int = get_env_int("MIN_MEMBER_COUNT", 50)

SESSION_STRINGS: list[str] = [getenv(f"STRING{i}", None) for i in range(1, 11)]
SESSION_STRINGS = [s for s in SESSION_STRINGS if s]

OWNER_ID: int = get_env_int("OWNER_ID", 5843255740)
LOGGER_ID: int = get_env_int("LOGGER_ID", 0)
MONGO_URI: Optional[str] = getenv("mongodb+srv://rohitgolu436:rohitgolu436@cluster0.4hnolvz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
API_URL: Optional[str] = getenv("https://sp.ashok.sbs")
API_KEY: Optional[str] = getenv("eafad9_9WtXLjf4GAW66HlDTs3Jp_U3kT7BhcWV")
PROXY: Optional[str] = getenv("PROXY")

DEFAULT_SERVICE: str = getenv("DEFAULT_SERVICE", "youtube").lower()
DOWNLOADS_DIR: Path = Path(getenv("DOWNLOADS_DIR", "database/music"))
SUPPORT_GROUP: str = getenv("SUPPORT_GROUP", "https://t.me/+80p30HSfA7g4ZTA9")
SUPPORT_CHANNEL: str = getenv("SUPPORT_CHANNEL", "https://t.me/+80p30HSfA7g4ZTA9")

IGNORE_BACKGROUND_UPDATES: bool = (
    getenv("IGNORE_BACKGROUND_UPDATES", "True").lower() == "true"
)
AUTO_LEAVE: bool = getenv("AUTO_LEAVE", "True").lower() == "true"


def process_cookie_urls(env_value: Optional[str]) -> list[str]:
    """Parse COOKIES_URL for one or more valid URLs."""
    if not env_value:
        return []
    parts = env_value.replace(",", " ").split()
    return [url.strip() for url in parts if url.strip()]


COOKIES_URL: list[str] = process_cookie_urls(getenv("COOKIES_URL", ""))

# Developer IDs (OWNER_ID is always included)
devs_env: Optional[str] = getenv("DEVS")
DEVS: list[int] = list(map(int, devs_env.split())) if devs_env else []
if OWNER_ID and OWNER_ID not in DEVS:
    DEVS.append(OWNER_ID)
